/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_core_WRAP_H_
#define SWIG_core_WRAP_H_

class SwigDirector_NativeNotificationCenter : public core::NotificationCenter, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_NativeNotificationCenter(JNIEnv *jenv);
    virtual void notify(int resourceId, int key) const;
    virtual void notifyList(int resourceId) const;
    virtual ~SwigDirector_NativeNotificationCenter();
public:
    bool swig_overrides(int n) {
      return (n < 2 ? swig_override[n] : false);
    }
protected:
    bool swig_override[2];
};


#endif
