/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ch.vbckantibaden.android.core;

public class core {

  private static class NativeNotificationCenterProxy extends NativeNotificationCenter {
    private NotificationCenter delegate;
    public NativeNotificationCenterProxy(NotificationCenter nc) {
      delegate = nc;
    }

    public void notify(int resourceId, int key) {
      delegate.notify(resourceId, key);
    }
    
    public void notifyList(int resourceId) {
      delegate.notifyList(resourceId);
    }
  }

  public static NativeNotificationCenter makeNative(NotificationCenter nc) {
    if (nc instanceof NativeNotificationCenter) {
      // If it already *is* a NativeNotificationCenter don't bother wrapping it again
      return (NativeNotificationCenter)nc;
    }
    return new NativeNotificationCenterProxy(nc);
  }

}
