/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ch.vbckantibaden.android.core;

public class coreJNI {
  public final static native void NativeNotificationCenter_notify(long jarg1, NativeNotificationCenter jarg1_, int jarg2, int jarg3);
  public final static native void NativeNotificationCenter_notifyList(long jarg1, NativeNotificationCenter jarg1_, int jarg2);
  public final static native void delete_NativeNotificationCenter(long jarg1);
  public final static native long new_NativeNotificationCenter();
  public final static native void NativeNotificationCenter_director_connect(NativeNotificationCenter obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void NativeNotificationCenter_change_ownership(NativeNotificationCenter obj, long cptr, boolean take_or_release);
  public final static native long new_ResourceManager(long jarg1, NativeNotificationCenter jarg1_);
  public final static native void delete_ResourceManager(long jarg1);
  public final static native long ResourceManager_getPlayerForKey(long jarg1, ResourceManager jarg1_, int jarg2);
  public final static native void ResourceManager_notifyTestPlayer(long jarg1, ResourceManager jarg1_);

  static {
    try {
        System.loadLibrary("core");
    } catch (UnsatisfiedLinkError e) {
      System.err.println("Native code library failed to load. \n" + e);
      System.exit(1);
    }
  }


  public static void SwigDirector_NativeNotificationCenter_notify(NativeNotificationCenter self, int resourceId, int key) {
    self.notify(resourceId, key);
  }
  public static void SwigDirector_NativeNotificationCenter_notifyList(NativeNotificationCenter self, int resourceId) {
    self.notifyList(resourceId);
  }

  private final static native void swig_module_init();
  static {
    swig_module_init();
  }
}
