/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ch.vbckantibaden.android.core;

public class NativeNotificationCenter {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected NativeNotificationCenter(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NativeNotificationCenter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        coreJNI.delete_NativeNotificationCenter(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    coreJNI.NativeNotificationCenter_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    coreJNI.NativeNotificationCenter_change_ownership(this, swigCPtr, true);
  }

  public void notify(int resourceId, int key) {
    coreJNI.NativeNotificationCenter_notify(swigCPtr, this, resourceId, key);
  }

  public void notifyList(int resourceId) {
    coreJNI.NativeNotificationCenter_notifyList(swigCPtr, this, resourceId);
  }

  public NativeNotificationCenter() {
    this(coreJNI.new_NativeNotificationCenter(), true);
    coreJNI.NativeNotificationCenter_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
