/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ch.vbckantibaden.android.core;
import ch.vbckantibaden.android.listener.PlayerListener;
public class Player {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Player(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Player obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        modelsJNI.delete_Player(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void addListener(PlayerListener listener) {
    NotificationCenterImpl.getInstance().addPlayerListener(listener, this);
  }
  
  public void removeListener(PlayerListener listener) {
    NotificationCenterImpl.getInstance().removePlayerListener(listener, this);
  }

  public Player(int key) {
    this(modelsJNI.new_Player(key), true);
  }

  public int key() {
    return modelsJNI.Player_key(swigCPtr, this);
  }

  public int resourceId() {
    return modelsJNI.Player_resourceId(swigCPtr, this);
  }

  public String name() {
    return modelsJNI.Player_name(swigCPtr, this);
  }

}
