/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ch.vbckantibaden.android.models;

public class modelsJNI {
  public final static native long new_Player();
  public final static native String Player_name(long jarg1, Player jarg1_);
  public final static native void delete_Player(long jarg1);
}
