/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ch.vbckantibaden.android.models;

public class Player {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Player(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Player obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        modelsJNI.delete_Player(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Player() {
    this(modelsJNI.new_Player(), true);
  }

  public String name() {
    return modelsJNI.Player_name(swigCPtr, this);
  }

}
