/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ch.vbckantibaden.android.core.models;

public class modelsJNI {
  public final static native long new_Player();
  public final static native String Player_name(long jarg1, Player jarg1_);
  public final static native void Player_addObserver(long jarg1, Player jarg1_, long jarg2, NativePlayerObserver jarg2_);
  public final static native void Player_removeObserver(long jarg1, Player jarg1_, long jarg2, NativePlayerObserver jarg2_);
  public final static native void delete_Player(long jarg1);
  public final static native void NativePlayerObserver_update(long jarg1, NativePlayerObserver jarg1_, long jarg2, Player jarg2_);
  public final static native void delete_NativePlayerObserver(long jarg1);
  public final static native long new_NativePlayerObserver();
  public final static native void NativePlayerObserver_director_connect(NativePlayerObserver obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void NativePlayerObserver_change_ownership(NativePlayerObserver obj, long cptr, boolean take_or_release);

  static {
    try {
        System.loadLibrary("models");
    } catch (UnsatisfiedLinkError e) {
      System.err.println("Native code library failed to load. \n" + e);
      System.exit(1);
    }
  }


  public static void SwigDirector_NativePlayerObserver_update(NativePlayerObserver self, long player) {
    self.update((player == 0) ? null : new Player(player, false));
  }

  private final static native void swig_module_init();
  static {
    swig_module_init();
  }
}
