/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ch.vbckantibaden.android.core.models;

public class models {

  private static class NativePlayerObserverProxy extends NativePlayerObserver {
    private PlayerObserver delegate;
    public NativePlayerObserverProxy(PlayerObserver i) {
      delegate = i;
    }

    public void update(Player player) {
      delegate.update(player);
    }
  }

  public static NativePlayerObserver makeNative(PlayerObserver o) {
    if (o instanceof NativePlayerObserver) {
      // If it already *is* a NativePlayerObserver don't bother wrapping it again
      return (NativePlayerObserver)o;
    }
    return new NativePlayerObserverProxy(o);
  }

}
